name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux --no-sound-null-safety
      - uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux/x64/release/bundle
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --no-sound-null-safety
      - uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows/x64/Release/Runner
